port: 3000

db:
  type: postgres
  host: dpg-cvi50fjqf0us73b0u8pg-a.oregon-postgres.render.com
  port: 5432
  user: wikisj_colateral_user
  pass: wikisj_colateral_user
  db: wikisj_colateral
  ssl: true

bindIP: 0.0.0.0
logLevel: info
